final List<Map<String, dynamic>> mockPods = [
  {
    'name': 'Quiet Pod - Oxford Circus',
    'latitude': 51.5154,
    'longitude': -0.1419,
    'price': '£8/hour',
    'address': 'Oxford Circus, London W1B 3AG',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM'],
    'description': 'A quiet pod in the heart of bustling Oxford Circus',
  },
  {
    'name': 'Work Pod - Waterloo',
    'latitude': 51.5033,
    'longitude': -0.1147,
    'price': '£5/hour',
    'address': 'Waterloo Station, London SE1 7LY',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM', '2:00 PM'],
    'description': 'A functional working pod by Waterloo station',
  },
  {
    'name': 'Focus Pod - Covent Garden',
    'latitude': 51.5115,
    'longitude': -0.1234,
    'price': '£9/hour',
    'address': 'Covent Garden, London WC2E 8RF',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['9:00 AM', '11:00 AM', '1:00 PM', '3:00 PM', '4:00 PM'],
    'description':
        'The pod you need to Lock In - close to Covent Garden station',
  },
  {
    'name': 'Private Pod - Paddington',
    'latitude': 51.5155,
    'longitude': -0.1754,
    'price': '£12/hour',
    'address': 'Paddington Station, London W2 1RH',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['9:00 AM', '10:00 AM', '2:00 PM', '3:00 PM', '5:00 PM'],
    'description': 'A private pod close to the Elizabeth line station',
  },
  {
    'name': 'Quiet Space - Liverpool Street',
    'latitude': 51.5178,
    'longitude': -0.0815,
    'price': '£7/hour',
    'address': 'Liverpool Street, London EC2M 7PY',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['10:00 AM', '11:00 AM', '1:00 PM', '2:00 PM', '4:00 PM'],
    'description': 'A quiet pod next to Hotel Andaz',
  },
  {
    'name': 'Central Pod - King’s Cross',
    'latitude': 51.5306,
    'longitude': -0.1231,
    'price': '£5/hour',
    'address': 'King’s Cross Station, London N1C 4AP',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['9:00 AM', '12:00 PM', '2:00 PM', '3:00 PM', '4:00 PM'],
    'description': 'Hop of the Euro Star and get right to work',
  },
  {
    'name': 'Cozy Pod - Shoreditch',
    'latitude': 51.5260,
    'longitude': -0.0786,
    'price': '£10/hour',
    'address': 'Shoreditch High Street, London E1 6HU',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['9:00 AM', '10:00 AM', '11:00 AM', '3:00 PM', '5:00 PM'],
    'description': 'Near Shoreditch House and Shoreditch High Street Station',
  },
  {
    'name': 'Modern Pod - Canary Wharf',
    'latitude': 51.5054,
    'longitude': -0.0235,
    'price': '£13/hour',
    'address': 'Canary Wharf, London E14 5AB',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['10:00 AM', '12:00 PM', '1:00 PM', '3:00 PM', '4:00 PM'],
    'description': 'For the bankers out there',
  },
  {
    'name': 'Classic Pod - Victoria',
    'latitude': 51.4964,
    'longitude': -0.1431,
    'price': '£4/hour',
    'address': 'Victoria Station, London SW1E 5ND',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['9:00 AM', '10:00 AM', '11:00 AM', '1:00 PM', '2:00 PM'],
    'description':
        'Got a sudden meeting right before your coach home? We got you covered',
  },
  {
    'name': 'Executive Pod - London Bridge',
    'latitude': 51.5055,
    'longitude': -0.0873,
    'price': '£8/hour',
    'address': 'London Bridge, London SE1 9SP',
    'imageUrl': 'https://via.placeholder.com/300x200',
    'schedule': ['9:00 AM', '11:00 AM', '12:00 PM', '3:00 PM', '5:00 PM'],
    'description': 'Close to Borough Market',
  },
];
