// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCyb7sdcJFQc3hHnzKFMYTXkEXi0-34aU',
    appId: '1:392686379506:web:c773ff79abbbb86feb4b6b',
    messagingSenderId: '392686379506',
    projectId: 'qwip-app-8ac86',
    authDomain: 'qwip-app-8ac86.firebaseapp.com',
    storageBucket: 'qwip-app-8ac86.firebasestorage.app',
    measurementId: 'G-EH9XQQEE0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx4muYhudqmY8Au_afTk-2EEazfHfxL_E',
    appId: '1:392686379506:android:0d9654dd24e08f40eb4b6b',
    messagingSenderId: '392686379506',
    projectId: 'qwip-app-8ac86',
    storageBucket: 'qwip-app-8ac86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnvvFyE2oEpH2NOc1d7BsGRWhDO-AFX_w',
    appId: '1:392686379506:ios:1c5f5e7bc509a962eb4b6b',
    messagingSenderId: '392686379506',
    projectId: 'qwip-app-8ac86',
    storageBucket: 'qwip-app-8ac86.firebasestorage.app',
    iosBundleId: 'com.example.qwipApp',
  );

}